FROM node:14-alpine3.12

ENV NODE_ENV=${NODE_ENV}
ENV PORT=${PORT}
ENV POSTGRES_HOST=${POSTGRES_HOST}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRESS_PASSWORD=${POSTGRESS_PASSWORD}
ENV POSTGRESS_PORT=${POSTGRESS_PORT}
ENV PRIVATE_KEY=${PRIVATE_KEY}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "start"]
